### ISSUE TITLE
Support configuration on source branch

### ISSUE THREAD

**Issue by ZryletTC** [goerz/doctr_versions_menu#6]
Hi again,

I noticed your issue in the doctr repo, https://github.com/drdoctr/doctr/issues/353, and was hoping for the same reasons that the configuration file `doctr-versions-menu.conf` could be placed in the source branch instead of on `gh-pages`.

I couldn't tell if your issue in doctr was with the goal of allowing this or for something else entirely. Either way, I thought to make an issue to have it noted here.

**Comment by goerz** [comment]
I think that would be feasible

**Comment by goerz** [comment]
I can't really think of a way to implement reading the config file from another branch without adding lots of complications:

First, we'd have to tell `doctr-versions-menu` where to get its config file, which is difficult. One could have a syntax like `--config=master:doctr-versions-menu.conf`, i.e. give a branch name prefix separated by a colon, but this may clash with Windows path names (`C://...`). We also don't necessarily know what the "source" branch is: we could look as Travis environment variables, but these are not necessarily set if `doctr-versions-menu` is run manually. The `versions.py` script that is generated on the `gh-pages` should also reliably reproduce the configuration that generated it in the first place, and it would be tricky for that script to know where it finds the correct configuration.

Second, we'd have to read data from a git branch other than the `gh-pages` branch we're currently on when the `doctr-versions-menu` script runs. Presumably, that could be done with the `gitpython` library, but that adds its own complications (and another dependency).

I think a better way is to allow all configuration to take place via environment variables. These can be set in the `.travis.yml` file on the source branch, and persist switching to the `gh-pages` branch. This solution is very easy to implement, too, since [`click` supports environment variables out of the box](https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables)

**Comment by goerz** [comment]
Support for environment variables is now merged into the latest `master`, and is documented in the sections about the [command line options](https://goerz.github.io/doctr_versions_menu/master/command.html#command-line-options) and [customization](https://goerz.github.io/doctr_versions_menu/master/command.html#customization)
